---
title: "Advanced Rmarkdown"
author: "Juan Carlos Villaseñor"
date: "13 de enero de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Talk 1

##`rticles` package

  - [GitHub Repository](https://www.github.com/rstudio/rticles)

  - LaTeX templates for Pandoc
  

## `tufte` package

  - tufte allows a main column for the body and a smaller side column for figs, sidenotes, or any other stuff
  
  - This package has the `full.width = TRUE` option in the code chunks
  
  - Package created in a responsive environment. Sidenotes become hidden in smaller screens, and can be accessed by clicking on body text that references them.
  
## `xaringan` package
  
  - Allows a more friendly interface for html output and presentation
  
  - slides in presentation mode
  
  - blackout screen, flip screen
  
## `bookdown` package

  - Multiple Rmarkdown documents, and allows you to produce a book
  
  - Output formats for \*.pdf, \*.html, and e-books
  
  - https://bookdown.org/yihui/bookdown/
  
  - Cross-referenced figures supported
  
  
# Talk 2

## Customize Rmd

  - First, check existing options in the Rmd page
  
  - Rmarkdown calls Knitr, which translates everything into Markdown, and then calls pandoc, which translates everything into the desired output
  
  
  
  
